require("mini.ai").setup()
require("mini.pairs").setup()
require("mini.surround").setup()
require("mini.icons").setup()
MiniIcons.mock_nvim_web_devicons()

require("flash").setup()
vim.keymap.set({ "n", "x", "o" }, "s", function()
  require("flash").jump()
end, { desc = "Flash" })
vim.keymap.set({ "n", "x", "o" }, "S", function()
  require("flash").treesitter()
end, { desc = "Flash Treesitter" })

require("grug-far").setup()
vim.keymap.set("n", "<leader>sr", function()
  require("grug-far").open()
end, { desc = "Search and Replace" })

require("persistence").setup()
vim.keymap.set("n", "<leader>qs", function()
  require("persistence").load()
end, { desc = "Restore Session" })
vim.keymap.set("n", "<leader>qS", function()
  require("persistence").select()
end, { desc = "Select Session" })
vim.keymap.set("n", "<leader>ql", function()
  require("persistence").load({ last = true })
end, { desc = "Last Session" })
vim.keymap.set("n", "<leader>qd", function()
  require("persistence").stop()
end, { desc = "Don't Save Session" })
